config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'strategem', to: 'strategems#index'
  resource :prospects
  get '*path', :to => 'application#page_not_found'
end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true
  validates :phone, :presence => true
  validates :description, :presence => true
  validates :budget, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def page_not_found
    flash[:error] = "That page does not exist"
    redirect_to :root
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController

  def index
  end

  def show
  end

  def new
    @prospect = Prospect.new
  end

  def create
    @prospect = Prospect.new(prospect_params)
    if @prospect.save
      UserNotifier.send_prospect_confirm_email(@prospect).deliver
      UserNotifier.send_prospect_notification_email(@prospect).deliver
      redirect_to :root
    else
      redirect_to new_prospects_path
    end
  end

private
  def prospect_params
    params.require(:prospect). permit(:name, :phone, :email, :description, :timetable, :referral, :budget)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end

end

app/controllers/strategems_controller.rb
class StrategemsController < ApplicationController

  def index

  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="col-sm-12">

</footer>

app/views/layouts/_header.html.erb
<header class="">
  <hgroup>
    <h1>
      <a href="/" rel="index">
      <span class="duane">Duane</span><span class="space">&nbsp;</span><span class="moody">Moody</span>
      </a>
    </h1>
    <h2>Software Developer</h2>
  </hgroup>
<!--   <aside>
  <span class="what">code <span class="amp">&amp;</span> rants</span> of
  <a href="http://duanemoody.io/" rel="me"><strong class="who">Duane M. Moody</strong></a><span class="period">.</span>
  </aside> -->
  <%= render 'layouts/navigation' %>
</header>

app/views/layouts/_navigation.html.erb
<div class="header-nav pull-right">
  <nav role="navigation">
    <ul class="list-inline">
      <li class="pull-right">
        <ul class="list-inline spread-space">
          <li><%= link_to "hire me", new_prospects_path %></li>
          <li><%= link_to "strategem", strategem_path %></li>
          <li><a href="#">blog</a></li>
        </ul>
      </li>         
    </ul>    
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Duane M. Moody</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-67531151-1', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body>
  <!-- Google Tag Manager -->
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PQHQZ4"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-PQHQZ4');</script>
  <!-- End Google Tag Manager -->
  <div class="container">
    
    <%= render 'layouts/header' %>

    <div class="website-content" role="main">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    
  </div>
</body>
</html>

app/views/prospects/_form.html.erb
<%= form_for @prospect do |f| %>
  <div class="form-group col-sm-12">
    <%= f.text_field :name, placeholder: "What is your name?", class: 'form-control col-sm-12' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.text_field :email, placeholder: "What is your email address?", class: 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.text_field :phone, placeholder: "What is your phone number?", class: 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.text_area :description, placeholder: "What would you like to hire me to do for you?", rows: 10, class: 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.text_field :budget, placeholder: "What is your budget?", class: 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.text_field :timetable, placeholder: "What is your timeframe for the project?", class: 'form-control' %>
  </div>
  <div class="form-group col-sm-12">
    <%= f.text_field :referral, placeholder: "How did you hear about me?", class: 'form-control' %>
  </div>
  <div class="form-group pull-right">
    <%= f.submit "Submit", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/prospects/new.html.erb
<h1 class="header1">Let's get to work!</h1>

<%= render 'form' %>

app/views/static_pages/home.html.erb
<!-- <div class="splash">
  <h1 class="header1 text-center">Let's bring your product to life</h1>
  <p class="header2 text-center">I provide real world solutions for real world people</p>
</div> -->

<section id="wrapper">
  <div class="banner">
    <%= image_tag 'banner.jpg' %>
  </div>
</section>

app/views/static_pages/resume.html.erb
<h1>About</h1>
<div>
  <p>Eight years experience as a self-taught software developer and recent graduate of the Epicodus Code School with demonstrated knowledge in Ruby, Ruby on Rails, Python, Flask, Django, Sinatra, JavaScript, HTML, CSS, PHP, API's/Frameworks and SQL Database Management.  Proven track record in project management and process improvement initiatives with a focus on LEAN and Agile concepts.</p>

  <p>Frequently described as a proactive, motivated and innovative leader with a strong background in business, communications, research and analytics, I am regarded as a strong, passionate, effective leader across functions and regions. I leverage inclusive and collaborative partnerships to deliver sustained business and organizational growth. I consistently challenge myself and the status quo to push boundaries and raise the bar. My strengths are in change management, operating with discipline, leveraging technologies, and accountability behind agreed-to measures.</p>
</div>
<h1>Languages and Technologies</h1>
<div class="col-sm-12">
<table class="table">
<tr>
  <td>Ruby</td>
  <td>Ruby on Rails</td>
</tr>
  <td>Python</td>
  <td>Sinatra</td>
  <td>CSS</td>
  <td>Bootstrap</td>
</tr>
<tr>
  <td>JavaScript</td>
  <td>Django</td>
  <td>jQuery</td>
  <td>AngularJS</td>
  <td>EmberJs</td>
  <td>CoffeeScript</td>
</tr>
<tr>
  <td>HTML</td>
  <td>Flask</td>
  <td>Sass</td>
  <td>MySQL</td>
  <td>MS SQL</td>
  <td>PostgreSQL</td>
  <td>MongoDB</td>
</tr>
<tr>
  <td>ASP.NET MVC 5</td>
  <td>ActiveRecord</td>
  <td>Git</td>
  <td>GitHub</td>
  <td>Stash</td>
  <td>Linux</td>
</tr>
<tr>
  <td>PHP</td>
  <td>Mac</td>
  <td>Windows</td>
  <td>Command Line</td>
  <td>Jira</td>
  <td>Jenkins</td>
</tr>
<tr>
  <td>DNS</td>
  <td>SRV Records</td>
  <td>HTTP</td>
  <td>AJAX</td>
  <td>API’s</td>
</tr>
<tr>
  <td>TDD</td>
</tr>
</table>
</div>
<h1>Experience and Organizations</h1>
  <h2>Operation Code – Current Contributor</h2>
    <p>Operation Code is an organization that focuses on trailblazing a new career path opportunity for military veterans in software development and coding.</p>
    <ul>
      <li>Contributed to the Operation Code code base for their website at operationcode.org written in Ruby on Rails, JavaScript and PostgreSQL.</li>
    </ul>
  <h2>Code Scouts – Mentor, 2 years</h2>
    <p>Code Scouts was an organization that focused on opening opportunities to women in the tech industry by providing mentorship, resources, support and community to promote full and equal inclusion.</p>
    <ul>
      <li>Worked as a mentor for women interested in learning programming and assisted in the coordination of events.</li>
    </ul>
  <h2>Portland Python User Group – Current Participant, 5 years</h2>
    <p>Local Portland user group for Python enthusiasts with monthly presentations on Pythonic topics, hack nights, code sprints, and technical assistance for the local community.</p>
  <h2>Portland Ruby Brigade (PDXRuby) – Current Participant, 3 years</h2>
    <p>User group for Ruby programmers for developers interested in the language, implementations, tools, libraries, and frameworks.</p>
  <h2>Hack the People – Current Mentor and Mentee, 2 years</h2>
    <p>An organization that strives to enhance and increase the number of mentor and mentee relationships in the technical community.</p>

<h1>Online Profiles</h1>
  <ul class="list-unstyled">
    <li>LinkedIn – linkedin.com/in/dmmoody</li>
    <li>Github – github.com/dmmoody</li>
    <li>Treehouse – teamtreehouse.com/duanemoody</li>
  </ul>

<h1>Employment</h1>
<h2>Software Developer Intern CrowdCompass by CVENT 2015</h2>
  <p>
    Worked on the server team with Ruby on Rails, PostgreSQL, MongoDB in an Agile team environment.
  </p>
  <p>
    Successfully resolved numerous Bug issues and deployed those fixes into production.
  </p>
  <p>
    Developed and deployed a full feature branch that provided a new master administrative action. The new feature notified all account administrators that a new version of their application was ready for publication and deployment to the Apple Store and Google Play.
  </p>
<h2>Branch Manager, Project Manager EBMS  2009 - 2015</h2>
  <p>
    Worked with a team to redesign our web application written in Microsoft ASP .NET MVC. The application is utilized by clients, members, brokers and business associates to deliver accurate information regarding member eligibility, health claims status, client reports, and health plan administration.
  </p>
  <p>
    Developed a report manager tool, multiple workflow dashboards, and audit tools for the Claims Department utilizing Python, Flask, Django, and MS SQL.
  </p>
  <p>
    Created an audit and plan analysis tool for the CDHC department with Python, Django and MS SQL. 
  </p>
  <p>
    Successfully designed and implemented an Electronic Explanation of Benefits system for our members and business associates that resulted in a net increase profitability for the company of 4%.
  </p>
  <p>
    Lead a team in the implementation of an Automated Clearing House (ACH) payment processing system for the company which resulted in a sustained reduction in yearly operating expenses by 3%.
  </p>
  <p>
    Developed and maintained a company wide Content Management System (CMS) written in PHP that showed a measurable 15% increase in workforce efficiencies and satisfied compliance requirements by regulatory agencies.
  </p>
  <p>
    Frequently assisted the Database Admins to provide custom and detail reports requested by various departments through custom queries to the MS SQL databases.
  </p>
<h2>Paramedic American Medical Responsible  2003 - 2009</h2>
  <p>
    Responsible for the transportation and care of medically ill and traumatically injured patients in emergency and non-emergency situations.
  </p>
<h2>Aircraft Rescue Firefighter City of Billings  2000 - 2005</h2>
  <p>
    Ensured the maintenance/compliance of all FAA, Federal, State and Local regulations pertaining to airport operations and aircraft rescue readiness and response.
  </p>
  <p>
    Developed a computer based inventory system for maintaining maintenance and inventory tracking logs for all fire suppression tools and vehicles. Technologies utilized were MS Access and Visual Basic.
  </p>
  <p>
    Created an Incident Reporting System used to track all emergency calls and provide historical reports required by the Federal Aviation Administration (FAA) and the United States Fire Administration (USFA) National Fire Incident Reporting System (NFIRS).  Technologies utilized were MS Access and Visual Basic.
  </p>

<h2>Education</h2>
<p>Software Development  Epicodus  Winter 2015</p>
<p>Software Development  Treehouse, Inc. 2008 – Current</p>
<p>PHP and Database Administration Portland Community College  Summer 2006</p>
<p>BAS Organizational Communication  Montana State University  2007 – 2010</p>
<p>AAS Paramedicine  Montana State University - COT  2005 - 2007</p>
<p>AAS Criminology Tarrant County Community College  1991 - 1993</p>

app/views/user_notifier/send_prospect_confirm_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thank you, <%= @prospect.name %> for requesting a proposal!</h1>
    <p>Thank you for requesting a proposal.  I will review the information you submitted and contact you within two business days so that we may discuss your project further!</p>
    <p>Best regards,</p>
    <p>Duane M. Moody</p>
  </body>
</html>

app/views/user_notifier/send_prospect_notification_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p><strong>Name:</strong> <%= @prospect.name %></p>
    <p><strong>Email:</strong> <%= @prospect.email %></p>
    <p><strong>Phone:</strong> <%= @prospect.phone %></p>
    <p><strong>Description:</strong> <%= @prospect.description %></p>
    <p><strong>Budget:</strong> <%= @prospect.budget %></p>
    <p><strong>Timeframe:</strong> <%= @prospect.timetable %></p>
    <p><strong>Referred by:</strong> <%= @prospect.referral %></p>
  </body>
</html>